#
#   Copyright 2010 Ricoh Company, Ltd.
#
#   This file is part of Castoro.
#
#   Castoro is free software: you can redistribute it and/or modify
#   it under the terms of the GNU Lesser General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   Castoro is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU Lesser General Public License for more details.
#
#   You should have received a copy of the GNU Lesser General Public License
#   along with Castoro.  If not, see <http://www.gnu.org/licenses/>.
#

require 'rubygems'
require 'rake'
require 'rake/clean'
require 'rake/gempackagetask'
require 'rake/rdoctask'

spec = Gem::Specification.new do |s|
  s.name = 'castoro-gateway-kyotocabinet'
  s.version = '2.0.0'
  s.has_rdoc = true
  s.extra_rdoc_files = ['README.textile']
  s.summary = "Implementation by KyotoCabinet of gateway cache."
  s.description = s.summary
  s.files = %w(History.txt LICENSE README.textile COPYING.LESSER Rakefile) + Dir.glob("{ext,lib,spec}/**/*")
  s.require_path = "lib"
  s.required_ruby_version = ">= 1.9.2"
  s.authors = ['Castoro project']

  s.extensions = ["ext/extconf.rb"]

  s.add_dependency('castoro-gateway', '>=2.0.0')
  s.add_development_dependency('rspec', '>=2.0.0')
end

Rake::GemPackageTask.new(spec) do |p|
  p.gem_spec = spec
  p.need_tar = true
  p.need_zip = true
end

Rake::RDocTask.new do |rdoc|
  files =['README.textile', 'LICENSE', 'lib/**/*.rb']
  rdoc.rdoc_files.add(files)
  rdoc.main = "README.textile" # page to start on
  rdoc.title = "castoro-gateway Docs"
  rdoc.rdoc_dir = 'doc/rdoc' # rdoc output folder
  rdoc.options << '--line-numbers'
end

Dir['tasks/**/*.rake'].each { |t| load t }

task :default => [:spec]

