#! /bin/bash -e
#
# cagentd   starts and stops the Castoro Agent Daemon
#
# chkconfig: 345 90 10
# description: Castoro Agent Daemon
# config: /etc/castoro/pgctl.conf
# config: /etc/castoro/peer.conf
#

#
#   Copyright 2010 Ricoh Company, Ltd.
#
#   This file is part of Castoro.
#
#   Castoro is free software: you can redistribute it and/or modify
#   it under the terms of the GNU Lesser General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   Castoro is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU Lesser General Public License for more details.
#
#   You should have received a copy of the GNU Lesser General Public License
#   along with Castoro.  If not, see <http://www.gnu.org/licenses/>.
#

export PATH=/usr/bin:/usr/sbin:/sbin:/usr/local/bin
script=cagentd

if [ ! -x /usr/local/bin/$script ] ; then
    exit 1
fi

config=/etc/castoro/pgctl.conf
if [ ! -f "$config" ] ; then
    echo "$0: cannot open $config"
    exit 1
fi

port=`/bin/awk '/^cagentd_comm_tcpport/ {print $2}' $config`
if [ -z "$port" ] ; then
    echo "$0: cagentd_comm_tcpport cannot be found in $config"
    exit 1
fi

case "$1" in
    'start')
    	/usr/local/bin/$script
	;;

    'stop')
	echo "Stopping $script ... "
	/usr/local/bin/ruby <<EOF
require 'socket'
print "Stopping " + "$script" + " ... "
begin
  begin
    s = TCPSocket.new "localhost", $port
    s.syswrite "[\"1.1\",\"C\",\"SHUTDOWN\",null]\n"
    x = s.gets
    puts x if x
  rescue Errno::ECONNREFUSED => e
    puts "Already stopped"
    exit 1
  end
  sleep 2
  begin
    s=TCPSocket.new "localhost", $port
  rescue Errno::ECONNREFUSED => e
    puts "OK"
  end
rescue => e
  p e
  exit 1
end
EOF
	;;

    *)
	echo "Usage: $0 { start | stop }"
	exit 1
	;;
esac
exit 0
