#! /bin/bash -e
#
#   Copyright 2010 Ricoh Company, Ltd.
#
#   This file is part of Castoro.
#
#   Castoro is free software: you can redistribute it and/or modify
#   it under the terms of the GNU Lesser General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   Castoro is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU Lesser General Public License for more details.
#
#   You should have received a copy of the GNU Lesser General Public License
#   along with Castoro.  If not, see <http://www.gnu.org/licenses/>.
#

export PATH=/usr/bin:/usr/sbin:/sbin:/usr/local/bin
script=cstartd

config=/etc/castoro/groupctl.conf
if [ ! -f "$config" ] ; then
    echo "$0: cannot open $config"
    exit 1
fi

port=`/bin/awk '/^cstartd_comm_tcpport/ {print $2}' $config`
if [ -z "$port" ] ; then
    echo "$0: cstartd_comm_tcpport cannot be found in $config"
    exit 1
fi

case "$1" in
    'start')
    	/usr/local/bin/$script
	;;

    'stop')
	echo "Stopping $script ... "
	/usr/local/bin/ruby -e "\
require 'socket'; \
printf '%s', 'Stopping ' + \"$script\" + ' ... '; \
begin; \
  s=TCPSocket.new 'localhost', $port; \
  s.puts '[\"1.1\",\"C\",\"SHUTDOWN\",null]'; \
  x=s.gets; \
  puts x if x; \
rescue Errno::ECONNREFUSED => e; \
  puts 'Already stopped'; \
  exit 1; \
rescue => e; \
  puts 'localhost:'+$port.to_s+': '+e.message; \
  exit 1; \
end; \
sleep 3; \
begin; \
  s=TCPSocket.new 'localhost', $port; \
rescue Errno::ECONNREFUSED => e; \
  puts 'OK'; \
rescue => e; \
  p e; \
end"
	;;

    *)
	echo "Usage: $0 { start | stop }"
	exit 1
	;;
esac
exit 0
