#!/bin/sh
# castoro-manipulator start/stop script.
# chkconfig: - 85 15
# description: castoro-manipulator start/stop script.
. /etc/rc.d/init.d/functions

prog=castoro-manipulatord

dir=`dirname \`which ruby\``
base=${dir}/castoro-manipulator

cnf=/etc/castoro/manipulator.conf
pid=/var/castoro/manipulator.pid
log=/var/castoro/manipulator.log
env=default

start() {
  echo $"Start Castoro-Manipulator ..."
  $base start -c $cnf -p $pid -l $log -e $env -d
}

stop() {
  echo $"Stop Castoro-Manipulator ..."
  $base stop -p $pid
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  status)
    status -p $pid $prog
    ;;
  *)
    echo $"Usage: $prog {start|stop|restart|status}"
esac

