#! /bin/bash

#
#   Copyright 2010 Ricoh Company, Ltd.
#
#   This file is part of Castoro.
#
#   Castoro is free software: you can redistribute it and/or modify
#   it under the terms of the GNU Lesser General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   Castoro is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU Lesser General Public License for more details.
#
#   You should have received a copy of the GNU Lesser General Public License
#   along with Castoro.  If not, see <http://www.gnu.org/licenses/>.
#

start_script=cmond
stop_script=cmond-stop
config=/etc/castoro/peer.conf

case "$1" in
  'start')
    ${start_script} -c $config
    ;;

  'stop')
    ${stop_script} -c $config
    ;;

  *)
    echo "Usage: $0 { start | stop }"
    exit 1
    ;;
esac

exit 0
