#! /bin/bash

#
#   Copyright 2010 Ricoh Company, Ltd.
#
#   This file is part of Castoro.
#
#   Castoro is free software: you can redistribute it and/or modify
#   it under the terms of the GNU Lesser General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   Castoro is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU Lesser General Public License for more details.
#
#   You should have received a copy of the GNU Lesser General Public License
#   along with Castoro.  If not, see <http://www.gnu.org/licenses/>.
#

config=/etc/castoro/peer.conf
port=`/bin/awk '/^cmond_maintenance_tcpport/ {print $2}' $config`
script=cmond

export PATH=/usr/bin:/usr/sbin:/sbin:/usr/local/bin

unset command
if [ -x /usr/local/bin/$script ]; then command=/usr/local/bin/$script; fi
if [ -x /usr/bin/$script ]; then command=/usr/bin/$script; fi
if [ -z "$command" ]; then echo $script is not found; exit 1; fi

unset ruby
if [ -x /usr/local/bin/ruby ]; then ruby=/usr/local/bin/ruby; fi
if [ -x /usr/bin/ruby ]; then ruby=/usr/bin/ruby; fi
if [ -z "$ruby" ]; then echo ruby is not found; exit 1; fi

case "$1" in
    'start')
	$command -c $config
	;;

    'stop')
	echo "$script is going to shutdown ... "
	$ruby -e "require 'socket'; begin s=TCPSocket.new 'localhost', $port; s.puts 'shutdown'; s.gets; rescue => e; puts e.message; end"
	;;

    *)
	echo "Usage: $0 { start | stop }"
	exit 1
	;;
esac
exit 0
