#!/bin/sh
# castoro-gateway start/stop script.
# chkconfig: - 85 15
# description: castoro-gateway start/stop script.
. /etc/rc.d/init.d/functions

PATH=/usr/local/bin:/usr/bin:/bin

prog=castoro-gatewayd

base=castoro-gateway
cnf=/etc/castoro/gateway.conf
pid=/var/castoro/gateway.pid
log=/var/castoro/gateway.log
env=default

start() {
  echo $"Start Castoro-Gateway ..."
  $base start -c $cnf -p $pid -l $log -e $env -d
}

stop() {
  echo $"Stop Castoro-Gateway ..."
  $base stop -p $pid
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  status)
    status -p $pid $prog
    ;;
  *)
    echo $"Usage: $prog {start|stop|restart|status}"
esac

