#! /bin/bash -e
#
#   Copyright 2010 Ricoh Company, Ltd.
#
#   This file is part of Castoro.
#
#   Castoro is free software: you can redistribute it and/or modify
#   it under the terms of the GNU Lesser General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   Castoro is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU Lesser General Public License for more details.
#
#   You should have received a copy of the GNU Lesser General Public License
#   along with Castoro.  If not, see <http://www.gnu.org/licenses/>.
#

export PATH=/usr/bin:/usr/sbin:/sbin:/usr/local/bin
script=cagentd

config=/etc/castoro/groupctl.conf
if [ ! -f "$config" ] ; then
    echo "$0: cannot open $config"
    exit 1
fi

port=`/bin/awk '/^cagentd_comm_tcpport/ {print $2}' $config`
if [ -z "$port" ] ; then
    echo "$0: cagentd_comm_tcpport cannot be found in $config"
    exit 1
fi

case "$1" in
    'start')
    	/usr/local/bin/$script
	;;

    'stop')
	echo "$script is going to shutdown ... "
	/usr/local/bin/ruby -e "require 'socket'; begin s=TCPSocket.new 'localhost', $port; s.puts '[\"1.1\",\"C\",\"SHUTDOWN\",null]'; x=s.gets; puts x if x; rescue => e; puts 'localhost:'+$port.to_s+': '+e.message; end"
	;;

    *)
	echo "Usage: $0 { start | stop }"
	exit 1
	;;
esac
exit 0
