#
#   Copyright 2010 Ricoh Company, Ltd.
#
#   This file is part of Castoro.
#
#   Castoro is free software: you can redistribute it and/or modify
#   it under the terms of the GNU Lesser General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   Castoro is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU Lesser General Public License for more details.
#
#   You should have received a copy of the GNU Lesser General Public License
#   along with Castoro.  If not, see <http://www.gnu.org/licenses/>.
#

target = 'password_reader.so'
dir = 'castoro-pgctl'
makefile = 'Makefile'
header_files = FileList[ ]
source_files = FileList[ 'password_reader.c' ]

task :default => [ target, "#{dir}/#{target}" ]

file makefile => %w( extconf.rb ) + header_files + source_files do
  sh "ruby extconf.rb"
end

file target => makefile do
  sh "make clean"
  sh "make"
end

file "#{dir}/#{target}" => target do
  sh "mkdir -p #{dir}"
  sh "cp #{target} #{dir}/#{target}"
end
